import pandas as pd
import plotly.express as px
charger_data = pd.read_csv('/2023051601_charger.csv')
obd_data = pd.read_csv('/2023051601_OBD.csv')
print(charger_data.head())
print(charger_data.describe())
print(obd_data.head())
print(obd_data.describe())
print("Charger Data Columns: ", charger_data.columns)
print("OBD Data Columns: ", obd_data.columns)
charger_data = charger_data[['datetime', 'voltage', 'current', 'soc', 'power', 'charged_energy']]
obd_data = obd_data[['datetime', 'voltage', 'current', 'soc', 'temperature']]
# charger_data['datetime'] = pd.to_datetime(charger_data['datetime'])
obd_data['datetime'] = pd.to_datetime(obd_data['datetime'])
avg_voltage = charger_data['voltage'].mean()
avg_current = charger_data['current'].mean()
avg_soc = charger_data['soc'].mean()
total_charged_energy = charger_data['charged_energy'].sum()
avg_voltage_obd = obd_data['voltage'].mean()
avg_current_obd = obd_data['current'].mean()
avg_soc_obd = obd_data['soc'].mean()
avg_temperature = obd_data['temperature'].mean()
fig1 = px.line(charger_data, x='datetime', y='voltage', title='Voltage over Time (Charger Data)')
fig1.write_html('charger_voltage.html')
fig2 = px.line(charger_data, x='datetime', y='soc', title='SOC over Time (Charger Data)')
fig2.write_html('charger_soc.html')
fig3 = px.line(obd_data, x='datetime', y='voltage', title='Voltage over Time (OBD Data)')
fig3.write_html('obd_voltage.html')
fig4 = px.line(obd_data, x='datetime', y='soc', title='SOC over Time (OBD Data)')
fig4.write_html('obd_soc.html')
fig5 = px.line(obd_data, x='datetime', y='temperature', title='Temperature over Time')
fig5.write_html('obd_temperature.html')
